"""empty message

Revision ID: d51a2b2f6199
Revises: 760b5aa6b054
Create Date: 2023-12-06 13:18:32.600822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51a2b2f6199'
down_revision = '760b5aa6b054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_index('ix_idea_text')

    op.drop_table('idea')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('likes')

    op.create_table('idea',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=500), nullable=True),
    sa.Column('upvotes', sa.INTEGER(), nullable=True),
    sa.Column('downvotes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.create_index('ix_idea_text', ['text'], unique=False)

    # ### end Alembic commands ###
